#ifndef NES_MEMORY_MAP_HH
#define NES_MEMORY_MAP_HH

//SIZE IN BITS
#define RAM_SIZE 2048
#define PPU_REGS_SIZE 8
#define APU_IO_REG_SIZE 24
#define CARTRIDGE_SPACE_SIZE 49120

#define INTERNAL_RAM_SIZE 0x0800

#define PPU_ADDR 0x2000
#define RAM_ADDR 0x0000
#define APU_IO_ADDR 0x4000
#define CARTRIDGE_ADDR 0x4020 //PRG ROM, PRG RAM, and mapper

#define PRG_ROM_UNIT_SIZE 16384
#define TRAINER_SIZE 512
#define TRAINER_LOAD_ADDR 0x7000


#define NTSC_NES_FREQ 21441960 

//CPU INTERRUPT VECTORS

#define NMI_IV_START_ADDR 0xFFFA
#define RESET_IV_START_ADDR 0xFFFC
#define IRQ_BRK_IV_START_ADDR 0xFFFE

#define INES_TRAINER_SIZE 512

#define STACK_START_ADDR 0x0100
#define STACK_END_ADDR 0x01FF
#define STACK_SIZE (STACK_END_ADDR - STACK_START_ADDR)
#define STACK_INIT_VALUE 0xFF



//mem map
#define CPU_RAM_START_ADDR 0x0000
#define IO_REGISTERS_START_ADDR 0x2000
#define EXPANSION_ROM_START_ADDR 0x4020
#define SAVE_RAM_START_ADDR 0x6000
#define PRG_ROM_START_ADDR 0x4020

#define CPU_RAM_SIZE (EXPANSION_ROM_START_ADDR-CPU_RAM_START_ADDR)
#define IO_REGS_SIZE (EXPANSION_ROM_START_ADDR-IO_REGISTERS_START_ADDR)
#define EXPANSION_ROM_SIZE (SAVE_RAM_START_ADDR-EXPANSION_ROM_START_ADDR)
#define SAVE_RAM_SIZE (PRG_ROM_START_ADDR-SAVE_RAM_START_ADDR)
#define PRG_ROM_SIZE (0xFFFF-PRG_ROM_START_ADDR)


#endif
